// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestingHW
{
    [TestFixture, Order(4)]
    public class DeletePostTest : AuthBase
    {
        [Test]
        public void deletePost()
        {
            app.Poster.DeleteLastPost();
            Assert.IsTrue(app.Poster.DeletionAlertIsPresent());
        }
    }
}