// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestingHW
{
    [TestFixture, Order(3)]
    public class EditPostTest : AuthBase
    {
        [Test]
        public void editPost()
        {
            string editString = DateTime.Now.ToString();
            string postId = "k9ekpk";
            app.Poster.EditThePost(postId, editString);
            Assert.AreEqual(editString, app.Poster.CurrentPostContent());
        }
    }
}