// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestingHW
{
    [TestFixture, Order(1)]
    public class LoginTests : TestBase
    {
        [Test, Order(2)]
        public void LoginWithValidData()
        {
            app.Auth.Logout();
            app.Auth.Login(new AccountData(Settings.Login, Settings.Password));

            Assert.AreEqual(Settings.Login, app.Auth.GetUsername());
        }

        [Test, Order(1)]
        public void LoginWithInvalidData()
        {
            AccountData data = new AccountData(Settings.Login, Settings.Password + "s");

            app.Auth.Logout();
            app.Auth.Login(data);

            Assert.IsTrue(app.Auth.InvalidDataWasSent());
        }
    }
}