// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestingHW
{
    [TestFixture, Order(5)]
    public class LogoutTest : AuthBase
    {
        [Test]
        public void loginAndLogout()
        {
            app.Auth.Logout();
            Assert.IsFalse(app.Auth.IsLoggedIn());
        }
    }
}
