// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.IO;
using System.Xml.Serialization;

namespace TestingHW
{
    [TestFixture, Order(2)]
    public class SelfpostTest : AuthBase
    {
        [Test, TestCaseSource("PostDataFromXmlFile")]
        public void loginAndSelfpost(PostData postData)
        {
            app.Poster.MakeASelfpost(postData);
            Assert.AreEqual(postData.Title, app.Poster.CurrentPostTitle());
            Assert.AreEqual(postData.Content, app.Poster.CurrentPostContent());
        }

        public static IEnumerable<PostData> PostDataFromXmlFile()
        {
            return (List<PostData>)new XmlSerializer(typeof(List<PostData>))
                .Deserialize(new StreamReader(@"Z:\posts.xml"));
        }
    }
}
